import Config

# Application config
config :opus,
  oanda_base_url: System.get_env("OANDA_BASE_URL") || "https://api-fxpractice.oanda.com",
  oanda_account_id: System.get_env("OANDA_ACCOUNT_ID"),
  oanda_api_key: System.get_env("OANDA_API_KEY")

# Configure your database
config :opus, Opus.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "auro",
  port: 5432,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :opus, OpusWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4321],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "UcLuCZRQ30QCbvNRaJeY0KiWT0wn0uO9KecSwuCh2kVikSLxokescXkxA6RyckVR",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :opus, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
# config :swoosh, :api_client, false
