defmodule Opus.Repo.Migrations.CreateStrategyConfigs do
  use Ecto.Migration

  @doc """
  Stores strategy parameter configs generated by Ollama (or entered manually)
  before they enter the validation pipeline.

  Ownership: Opus owns this table. Rust receives configs via HTTP and runs them,
  but never writes to this table.

  No FK to live_strategies — a config only becomes a live strategy if it passes
  all three validation gates. The promotion step creates the live_strategies row.

  parent_config_id tracks lineage: when Ollama generates a revised config based
  on a failed evaluation, it points back to the config that failed.
  """
  def change do
    create table(:strategy_configs, primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :source, :string, null: false, default: "ollama"
      add :instrument, :string, null: false
      add :granularity, :string, null: false
      add :strategy_type, :string, null: false
      add :parameters, :map, null: false
      add :parent_config_id, :binary_id

      timestamps(type: :utc_datetime_usec)
    end

    create index(:strategy_configs, [:instrument, :granularity, :strategy_type])
    create index(:strategy_configs, [:parent_config_id])
  end
end
