ALTER TABLE candles
  ADD COLUMN bid_open DOUBLE PRECISION,
  ADD COLUMN bid_high DOUBLE PRECISION,
  ADD COLUMN bid_low DOUBLE PRECISION,
  ADD COLUMN bid_close DOUBLE PRECISION,
  ADD COLUMN ask_open DOUBLE PRECISION,
  ADD COLUMN ask_high DOUBLE PRECISION,
  ADD COLUMN ask_low DOUBLE PRECISION,
  ADD COLUMN ask_close DOUBLE PRECISION;
